name: Test GITHUB_SHA
on: [push]

jobs:
  test-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GITHUB_SHA for Next.js
        if: matrix.service == 'app'
        run: |
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Debug GITHUB_SHA and BUILD_ID
        run: |
          echo "GITHUB_SHA value is: ${{ github.sha }}"
          echo "GITHUB_SHA value from env: $GITHUB_SHA" # Access the GITHUB_SHA environment variable
          echo "Full github context:"
          echo "${{ toJSON(github) }}"
