name: Test GITHUB_SHA
on: [push]

jobs:
  test-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GITHUB_SHA for Next.js
        if: matrix.service == 'app'
        run: |
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Debug GITHUB_SHA and BUILD_ID
        run: |
          echo "GITHUB_SHA value is: ${{ github.sha }}"
          echo "BUILD_ID value from env: $BUILD_ID" # Access the BUILD_ID environment variable
          echo "Full github context:"
          echo "${{ toJSON(github) }}"
